spring.application.name=prepwise
# PostgreSQL DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/prepwise_db
spring.datasource.username=postgres
spring.datasource.password=PgMarvel@241

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
